version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    env_file:
      - .env.production
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quicktransfer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
