name: Deploy via SSH

on:
  push:
    branches: ["dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Configure Cloudflared with Service Token
        run: |
          mkdir -p ~/.cloudflared
          echo "credentials-file: /home/runner/.cloudflared/credentials.json" > ~/.cloudflared/config.yml
          # Create credentials.json
          cat <<EOF > /home/runner/.cloudflared/credentials.json
          {
            "AccessToken": "${{ secrets.CLOUDFLARE_SERVICE_TOKEN_ID }}",
            "AccessSecret": "${{ secrets.CLOUDFLARE_SERVICE_TOKEN_SECRET }}"
          }
          EOF

      - name: SSH into Server
        run: |
          cloudflared access ssh --hostname ${{secrets.SERVERSSH}} -- ssh @${{secrets.SERVERSSH}} "echo 'Hello from GitHub Actions' && mkdir test"
